using NFluent;
using NUnit.Framework;
using System;
using System.IO;
using System.Text;

namespace csharp.Test
{
    [TestFixture]
    public class ApprovalTest
    {
        [Test]
        public void ThirtyDays()
        {

            var fakeoutput = new StringBuilder();
            Console.SetOut(new StringWriter(fakeoutput));
            Console.SetIn(new StringReader("a\n"));

            Program.Main(new string[] { });

            var outputExpected = "OMGHAI!\r\n" +
                "-------- day 0 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 10, 20\r\nAged Brie, 2, 0\r\nElixir of the Mongoose, 5, 7\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 15, 20\r\nBackstage passes to a TAFKAL80ETC concert, 10, 49\r\nBackstage passes to a TAFKAL80ETC concert, 5, 49\r\nConjured Mana Cake, 3, 6\r\n\r\n" +
                "-------- day 1 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 9, 19\r\nAged Brie, 1, 1\r\nElixir of the Mongoose, 4, 6\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 14, 21\r\nBackstage passes to a TAFKAL80ETC concert, 9, 50\r\nBackstage passes to a TAFKAL80ETC concert, 4, 50\r\nConjured Mana Cake, 2, 5\r\n\r\n" +
                "-------- day 2 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 8, 18\r\nAged Brie, 0, 2\r\nElixir of the Mongoose, 3, 5\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 13, 22\r\nBackstage passes to a TAFKAL80ETC concert, 8, 50\r\nBackstage passes to a TAFKAL80ETC concert, 3, 50\r\nConjured Mana Cake, 1, 4\r\n\r\n" +
                "-------- day 3 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 7, 17\r\nAged Brie, -1, 4\r\nElixir of the Mongoose, 2, 4\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 12, 23\r\nBackstage passes to a TAFKAL80ETC concert, 7, 50\r\nBackstage passes to a TAFKAL80ETC concert, 2, 50\r\nConjured Mana Cake, 0, 3\r\n\r\n" +
                "-------- day 4 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 6, 16\r\nAged Brie, -2, 6\r\nElixir of the Mongoose, 1, 3\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 11, 24\r\nBackstage passes to a TAFKAL80ETC concert, 6, 50\r\nBackstage passes to a TAFKAL80ETC concert, 1, 50\r\nConjured Mana Cake, -1, 1\r\n\r\n" +
                "-------- day 5 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 5, 15\r\nAged Brie, -3, 8\r\nElixir of the Mongoose, 0, 2\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 10, 25\r\nBackstage passes to a TAFKAL80ETC concert, 5, 50\r\nBackstage passes to a TAFKAL80ETC concert, 0, 50\r\nConjured Mana Cake, -2, 0\r\n\r\n" +
                "-------- day 6 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 4, 14\r\nAged Brie, -4, 10\r\nElixir of the Mongoose, -1, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 9, 27\r\nBackstage passes to a TAFKAL80ETC concert, 4, 50\r\nBackstage passes to a TAFKAL80ETC concert, -1, 0\r\nConjured Mana Cake, -3, 0\r\n\r\n" +
                "-------- day 7 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 3, 13\r\nAged Brie, -5, 12\r\nElixir of the Mongoose, -2, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 8, 29\r\nBackstage passes to a TAFKAL80ETC concert, 3, 50\r\nBackstage passes to a TAFKAL80ETC concert, -2, 0\r\nConjured Mana Cake, -4, 0\r\n\r\n" +
                "-------- day 8 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 2, 12\r\nAged Brie, -6, 14\r\nElixir of the Mongoose, -3, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 7, 31\r\nBackstage passes to a TAFKAL80ETC concert, 2, 50\r\nBackstage passes to a TAFKAL80ETC concert, -3, 0\r\nConjured Mana Cake, -5, 0\r\n\r\n" +
                "-------- day 9 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 1, 11\r\nAged Brie, -7, 16\r\nElixir of the Mongoose, -4, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 6, 33\r\nBackstage passes to a TAFKAL80ETC concert, 1, 50\r\nBackstage passes to a TAFKAL80ETC concert, -4, 0\r\nConjured Mana Cake, -6, 0\r\n\r\n" +
                "-------- day 10 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, 0, 10\r\nAged Brie, -8, 18\r\nElixir of the Mongoose, -5, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 5, 35\r\nBackstage passes to a TAFKAL80ETC concert, 0, 50\r\nBackstage passes to a TAFKAL80ETC concert, -5, 0\r\nConjured Mana Cake, -7, 0\r\n\r\n" +
                "-------- day 11 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -1, 8\r\nAged Brie, -9, 20\r\nElixir of the Mongoose, -6, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 4, 38\r\nBackstage passes to a TAFKAL80ETC concert, -1, 0\r\nBackstage passes to a TAFKAL80ETC concert, -6, 0\r\nConjured Mana Cake, -8, 0\r\n\r\n" +
                "-------- day 12 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -2, 6\r\nAged Brie, -10, 22\r\nElixir of the Mongoose, -7, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 3, 41\r\nBackstage passes to a TAFKAL80ETC concert, -2, 0\r\nBackstage passes to a TAFKAL80ETC concert, -7, 0\r\nConjured Mana Cake, -9, 0\r\n\r\n" +
                "-------- day 13 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -3, 4\r\nAged Brie, -11, 24\r\nElixir of the Mongoose, -8, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 2, 44\r\nBackstage passes to a TAFKAL80ETC concert, -3, 0\r\nBackstage passes to a TAFKAL80ETC concert, -8, 0\r\nConjured Mana Cake, -10, 0\r\n\r\n" +
                "-------- day 14 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -4, 2\r\nAged Brie, -12, 26\r\nElixir of the Mongoose, -9, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 1, 47\r\nBackstage passes to a TAFKAL80ETC concert, -4, 0\r\nBackstage passes to a TAFKAL80ETC concert, -9, 0\r\nConjured Mana Cake, -11, 0\r\n\r\n" +
                "-------- day 15 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -5, 0\r\nAged Brie, -13, 28\r\nElixir of the Mongoose, -10, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, 0, 50\r\nBackstage passes to a TAFKAL80ETC concert, -5, 0\r\nBackstage passes to a TAFKAL80ETC concert, -10, 0\r\nConjured Mana Cake, -12, 0\r\n\r\n" +
                "-------- day 16 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -6, 0\r\nAged Brie, -14, 30\r\nElixir of the Mongoose, -11, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -1, 0\r\nBackstage passes to a TAFKAL80ETC concert, -6, 0\r\nBackstage passes to a TAFKAL80ETC concert, -11, 0\r\nConjured Mana Cake, -13, 0\r\n\r\n" +
                "-------- day 17 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -7, 0\r\nAged Brie, -15, 32\r\nElixir of the Mongoose, -12, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -2, 0\r\nBackstage passes to a TAFKAL80ETC concert, -7, 0\r\nBackstage passes to a TAFKAL80ETC concert, -12, 0\r\nConjured Mana Cake, -14, 0\r\n\r\n" +
                "-------- day 18 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -8, 0\r\nAged Brie, -16, 34\r\nElixir of the Mongoose, -13, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -3, 0\r\nBackstage passes to a TAFKAL80ETC concert, -8, 0\r\nBackstage passes to a TAFKAL80ETC concert, -13, 0\r\nConjured Mana Cake, -15, 0\r\n\r\n" +
                "-------- day 19 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -9, 0\r\nAged Brie, -17, 36\r\nElixir of the Mongoose, -14, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -4, 0\r\nBackstage passes to a TAFKAL80ETC concert, -9, 0\r\nBackstage passes to a TAFKAL80ETC concert, -14, 0\r\nConjured Mana Cake, -16, 0\r\n\r\n" +
                "-------- day 20 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -10, 0\r\nAged Brie, -18, 38\r\nElixir of the Mongoose, -15, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -5, 0\r\nBackstage passes to a TAFKAL80ETC concert, -10, 0\r\nBackstage passes to a TAFKAL80ETC concert, -15, 0\r\nConjured Mana Cake, -17, 0\r\n\r\n" +
                "-------- day 21 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -11, 0\r\nAged Brie, -19, 40\r\nElixir of the Mongoose, -16, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -6, 0\r\nBackstage passes to a TAFKAL80ETC concert, -11, 0\r\nBackstage passes to a TAFKAL80ETC concert, -16, 0\r\nConjured Mana Cake, -18, 0\r\n\r\n" +
                "-------- day 22 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -12, 0\r\nAged Brie, -20, 42\r\nElixir of the Mongoose, -17, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -7, 0\r\nBackstage passes to a TAFKAL80ETC concert, -12, 0\r\nBackstage passes to a TAFKAL80ETC concert, -17, 0\r\nConjured Mana Cake, -19, 0\r\n\r\n" +
                "-------- day 23 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -13, 0\r\nAged Brie, -21, 44\r\nElixir of the Mongoose, -18, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -8, 0\r\nBackstage passes to a TAFKAL80ETC concert, -13, 0\r\nBackstage passes to a TAFKAL80ETC concert, -18, 0\r\nConjured Mana Cake, -20, 0\r\n\r\n" +
                "-------- day 24 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -14, 0\r\nAged Brie, -22, 46\r\nElixir of the Mongoose, -19, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -9, 0\r\nBackstage passes to a TAFKAL80ETC concert, -14, 0\r\nBackstage passes to a TAFKAL80ETC concert, -19, 0\r\nConjured Mana Cake, -21, 0\r\n\r\n" +
                "-------- day 25 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -15, 0\r\nAged Brie, -23, 48\r\nElixir of the Mongoose, -20, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -10, 0\r\nBackstage passes to a TAFKAL80ETC concert, -15, 0\r\nBackstage passes to a TAFKAL80ETC concert, -20, 0\r\nConjured Mana Cake, -22, 0\r\n\r\n" +
                "-------- day 26 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -16, 0\r\nAged Brie, -24, 50\r\nElixir of the Mongoose, -21, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -11, 0\r\nBackstage passes to a TAFKAL80ETC concert, -16, 0\r\nBackstage passes to a TAFKAL80ETC concert, -21, 0\r\nConjured Mana Cake, -23, 0\r\n\r\n" +
                "-------- day 27 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -17, 0\r\nAged Brie, -25, 50\r\nElixir of the Mongoose, -22, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -12, 0\r\nBackstage passes to a TAFKAL80ETC concert, -17, 0\r\nBackstage passes to a TAFKAL80ETC concert, -22, 0\r\nConjured Mana Cake, -24, 0\r\n\r\n" +
                "-------- day 28 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -18, 0\r\nAged Brie, -26, 50\r\nElixir of the Mongoose, -23, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -13, 0\r\nBackstage passes to a TAFKAL80ETC concert, -18, 0\r\nBackstage passes to a TAFKAL80ETC concert, -23, 0\r\nConjured Mana Cake, -25, 0\r\n\r\n" +
                "-------- day 29 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -19, 0\r\nAged Brie, -27, 50\r\nElixir of the Mongoose, -24, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -14, 0\r\nBackstage passes to a TAFKAL80ETC concert, -19, 0\r\nBackstage passes to a TAFKAL80ETC concert, -24, 0\r\nConjured Mana Cake, -26, 0\r\n\r\n" +
                "-------- day 30 --------\r\nname, sellIn, quality\r\n+5 Dexterity Vest, -20, 0\r\nAged Brie, -28, 50\r\nElixir of the Mongoose, -25, 0\r\nSulfuras, Hand of Ragnaros, 0, 80\r\nSulfuras, Hand of Ragnaros, -1, 80\r\nBackstage passes to a TAFKAL80ETC concert, -15, 0\r\nBackstage passes to a TAFKAL80ETC concert, -20, 0\r\nBackstage passes to a TAFKAL80ETC concert, -25, 0\r\nConjured Mana Cake, -27, 0\r\n\r\n";

            Check.That(fakeoutput.ToString()).Equals(outputExpected);            
        }
    }
}
